site_name: aftctl
site_description: Facilitates the AFT deployment process
copyright: Made with ❤️ by aftctl contributors.
repo_name: edgarsilva948/aftctl
repo_url: https://github.com/edgarsilva948/aftctl


# Configuration
theme:
    name: 'material'
    favicon: 'static/favicon.ico'
    logo: 'static/logo.png'
    font:
        text: 'Segoe UI'
        code: 'Roboto Mono'
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: black
        accent: indigo
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        accent: indigo
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
    features:
      - header.autohide
      - navigation.instant
      - navigation.sections
      - navigation.top
      - search.highlight
      - search.share
      - search.suggest
      - content.code.annotate
      - content.tooltips
      - content.tabs.link
      - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/edgarsilva948/aftctl


nav:
  - Home: index.md
  - Introduction: intro.md
  - Installation: install.md
  - Deploy:
      - AFT: deploy/aft.md